/**
 * Android color resource exporter
 * Exports palette as Android XML color resources and Material color tokens
 */

/**
 * Convert RGB array to Android hex color string (#AARRGGBB or #RRGGBB)
 * @param {number[]} rgb - [r, g, b] values 0-255
 * @param {number} alpha - alpha 0-255, defaults to 255
 * @returns {string}
 */
function rgbToAndroidHex(rgb, alpha = 255) {
  const [r, g, b] = rgb;
  const toHex = (n) => n.toString(16).padStart(2, '0').toUpperCase();
  if (alpha < 255) {
    return `#${toHex(alpha)}${toHex(r)}${toHex(g)}${toHex(b)}`;
  }
  return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
}

/**
 * Export palette as Android XML color resources
 * @param {object[]} palette - annotated palette entries
 * @returns {string} XML content
 */
function exportAndroidColors(palette) {
  const lines = [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<resources>',
    `    <!-- Generated by palette-extract on ${new Date().toISOString().split('T')[0]} -->`,
  ];

  for (const entry of palette) {
    const hex = rgbToAndroidHex(entry.rgb);
    const name = entry.name
      ? entry.name.toLowerCase().replace(/[^a-z0-9]+/g, '_')
      : `palette_color_${entry.index}`;
    lines.push(`    <color name="${name}">${hex}</color>`);
  }

  lines.push('</resources>');
  return lines.join('\n') + '\n';
}

/**
 * Export palette as Material Design color tokens (XML)
 * Generates primary, secondary, etc. based on palette order
 * @param {object[]} palette - annotated palette entries
 * @returns {string} XML content
 */
function exportMaterialColors(palette) {
  const roles = ['primary', 'secondary', 'tertiary', 'error', 'surface', 'background'];

  const lines = [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<resources>',
    `    <!-- Material color tokens generated by palette-extract -->`,
  ];

  palette.forEach((entry, i) => {
    const hex = rgbToAndroidHex(entry.rgb);
    const role = roles[i] || `custom_${i}`;
    lines.push(`    <color name="md_${role}">${hex}</color>`);
    // Add on-color (white or black based on luminance)
    const [r, g, b] = entry.rgb;
    const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
    const onColor = luminance > 0.5 ? '#000000' : '#FFFFFF';
    lines.push(`    <color name="md_on_${role}">${onColor}</color>`);
  });

  lines.push('</resources>');
  return lines.join('\n') + '\n';
}

module.exports = { rgbToAndroidHex, exportAndroidColors, exportMaterialColors };
